using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Gacha.Core;
using Gacha.Core.Battle;
using Gacha.Core.Campaign;
using Gacha.Core.Data;

namespace Gacha.Tests.Tools
{
    /// <summary>
    /// Builds Data/stages.json: 20 chapters × 30 stages, each enemy team chosen from the roster and its level
    /// sim-checked against reference teams at the expected level (Game Modes and Progression Plan, Campaign).
    /// Run: pwsh -File tools/csharp/test.ps1 -Main Gacha.Tests.Tools.StageGen   (args: seed=1, battlesPerCheck=80)
    /// </summary>
    public static class StageGen
    {
        /// <summary>The 12 synergy packages in decisions row 30's order.</summary>
        public static readonly string[] Packages =
            { "Burn", "Soaked", "Wounds", "Hindered", "Dread", "Exposed", "Disrupted", "Gathered", "Lifesteal", "Stealth", "Tempo", "Guarded" };
        /// <summary>Homeland race of chapters 1-4, 5-8, 9-12, 13-16, 17-20.</summary>
        public static readonly string[] Homelands = { "high", "dark", "nature", "ocean", "arcane" };
        public static readonly string[] Template = { "tank", "dps", "dps", "healer", "support" };

        /// <summary>Weaker early enemies (owner, 2026-10-03): chapter 1 fields 3, chapter 2 fields 4, both without
        /// package preference on normal stages; gates there carry the package on all but one enemy.</summary>
        public static string[] EnemyTemplate(int chapter) =>
            chapter == 1 ? new[] { "tank", "dps", "healer" } : chapter == 2 ? new[] { "tank", "dps", "dps", "healer" } : Template;
        public const int Chapters = 20, PerChapter = 30;

        public static int Main(string[] args)
        {
            if (args.Length > 0 && args[0] == "repower") return Repower();
            ulong seed = args.Length > 0 ? ulong.Parse(args[0]) : 1;
            int battles = args.Length > 1 ? int.Parse(args[1]) : 80;
            var g = TestData.Game;
            var info = HeroInfo.Load();
            var refs = ReferenceTeams(seed, info);
            Console.WriteLine("Reference teams: " + string.Join(" | ", refs.Select(t => string.Join(", ", t))));
            var stages = new List<StageDef>();
            var sw = System.Diagnostics.Stopwatch.StartNew();
            for (int i = 1; i <= Chapters * PerChapter; i++)
            {
                var s = Build(i, seed, info);
                int level = Calibrate(g, s, refs, battles, seed, out double wr);
                int offset = level - Expected.Level(i);
                foreach (var e in s.Enemies) e.Level = level;
                s.Power = TeamPower.Of(g, s);
                s.FirstClear["gold"] = Math.Round(g.Idle.PerHour("gold", i));
                s.FirstClear["heroXp"] = Math.Round(g.Idle.PerHour("heroXp", i));
                stages.Add(s);
                if (s.Stage % 10 == 0)
                    Console.WriteLine($"{s.Id}  lvl {s.Enemies[0].Level,3} (expected {Expected.Level(i),3}, offset {offset,3})  ref win {wr:P0}  {string.Join("/", s.Packages)}  {sw.Elapsed.TotalSeconds:0}s");
            }
            const string schema = "Generated by Tests/Tools/StageGen (do not hand-edit; change the generator and re-run). Enemies are Hollow echoes of roster heroes (3 in chapter 1, 4 in chapter 2, then 5); level is the lowest (1-200) at which the best of 4 reference teams at the expected level wins 50-70% (last 5 stages of a chapter: 40-55%), or as close as one level step allows. firstClear = 1 h of that stage's idle loot.";
            File.WriteAllText(Path.Combine(TestData.Dir, "stages.json"), StageDef.ListToJson(stages, pretty: true, schema: schema) + "\n");
            Console.WriteLine($"Wrote {stages.Count} stages in {sw.Elapsed.TotalSeconds:0}s");
            return 0;
        }

        /// <summary>
        /// Recomputes only each stage's recommended power (after a power-formula change); enemy levels stay as tuned.
        /// Run: pwsh -File tools/csharp/test.ps1 -Main Gacha.Tests.Tools.StageGen repower
        /// </summary>
        static int Repower()
        {
            var g = TestData.Game;
            var path = Path.Combine(TestData.Dir, "stages.json");
            var root = Node.Of(Json.Parse(File.ReadAllText(path)));
            foreach (var s in g.Stages) s.Power = TeamPower.Of(g, s);
            File.WriteAllText(path, StageDef.ListToJson(g.Stages, pretty: true, schema: root.Str("_schema")) + "\n");
            Console.WriteLine($"Recomputed power for {g.Stages.Count} stages");
            return 0;
        }

        /// <summary>Roster facts the generator needs that the battle defs do not keep (packages).</summary>
        public sealed class HeroInfo
        {
            public string Id, Core, Role;
            public HashSet<string> Packages = new HashSet<string>();
            public static List<HeroInfo> Load()
            {
                var list = new List<HeroInfo>();
                foreach (var n in Node.Of(Json.Parse(File.ReadAllText(Path.Combine(TestData.Dir, "heroes.json")))).Nodes("heroes"))
                {
                    var h = new HeroInfo { Id = n.Str("id"), Core = n.Str("core"), Role = n.Str("role") };
                    foreach (var p in n.Strs("applies")) h.Packages.Add(p);
                    foreach (var p in n.Strs("payoffs")) h.Packages.Add(p);
                    list.Add(h);
                }
                return list;
            }
        }

        /// <summary>Four balanced teams (tank, dps, dps, healer, support) from the whole roster.</summary>
        public static List<List<string>> ReferenceTeams(ulong seed, List<HeroInfo> info)
        {
            var rng = new Rng(seed);
            var teams = new List<List<string>>();
            for (int t = 0; t < 4; t++)
            {
                var team = new List<string>();
                foreach (var role in Template)
                {
                    var pool = info.Where(h => h.Role == role && !team.Contains(h.Id)).ToList();
                    team.Add(pool[rng.Range(0, pool.Count)].Id);
                }
                teams.Add(team);
            }
            return teams;
        }

        public static string[] ChapterPackages(int chapter) => new[] { Packages[(2 * chapter - 2) % 12], Packages[(2 * chapter - 1) % 12] };

        /// <summary>Stage shape and enemy heroes (levels set later by Calibrate).</summary>
        public static StageDef Build(int index, ulong seed, List<HeroInfo> info)
        {
            int ch = Expected.Chapter(index), st = (index - 1) % PerChapter + 1;
            var s = new StageDef { Id = $"ch{ch:00}_s{st:00}", Index = index, Chapter = ch, Stage = st, Gate = st % 10 == 0, Boss = st == 30 };
            var rng = new Rng(seed * 1_000_003UL + (ulong)index);
            var pkgs = ChapterPackages(ch);
            string home = Homelands[(ch - 1) / 4];
            List<string> team;
            if (s.Gate)
            {
                string pkg = st == 30 ? pkgs[0] : pkgs[(st / 10 - 1) % 2];
                s.Packages.Add(pkg);
                var roles = EnemyTemplate(ch);
                team = GateTeam(pkg, roles, roles.Length - (ch <= 2 ? 1 : 0), rng, info);
            }
            else
            {
                s.Packages.AddRange(pkgs);
                team = NormalTeam(EnemyTemplate(ch), ch >= 3 ? pkgs : new string[0], home, rng, info);
            }
            int stars = Expected.Stars(ch);
            foreach (var h in team) s.Enemies.Add(new EnemyDef { Hero = h, Level = Expected.Level(index), Stars = stars });
            return s;
        }

        /// <summary>Template roles; the tank and first dps from the homeland race, the rest preferring chapter-package carriers.</summary>
        static List<string> NormalTeam(string[] roles, string[] pkgs, string home, Rng rng, List<HeroInfo> info)
        {
            var team = new List<string>();
            for (int k = 0; k < roles.Length; k++)
            {
                var pool = info.Where(h => h.Role == roles[k] && !team.Contains(h.Id)).ToList();
                if (k < 2) pool = pool.Where(h => h.Core == home).ToList();
                else
                {
                    var carriers = pool.Where(h => pkgs.Any(h.Packages.Contains)).ToList();
                    if (carriers.Count > 0) pool = carriers;
                }
                team.Add(pool[rng.Range(0, pool.Count)].Id);
            }
            return team;
        }

        /// <summary>Up to `carry` carriers of the package (one per template role first), then non-carriers by template role.</summary>
        static List<string> GateTeam(string pkg, string[] roles, int carry, Rng rng, List<HeroInfo> info)
        {
            var carriers = Shuffle(info.Where(h => h.Packages.Contains(pkg)).ToList(), rng);
            var team = new List<string>();
            foreach (var role in roles)
            {
                if (team.Count >= carry) break;
                var pick = carriers.FirstOrDefault(h => h.Role == role && !team.Contains(h.Id));
                if (pick != null) team.Add(pick.Id);
            }
            foreach (var h in carriers) { if (team.Count >= carry) break; if (!team.Contains(h.Id)) team.Add(h.Id); }
            var others = info.Where(h => !h.Packages.Contains(pkg)).ToList();
            foreach (var role in roles)
            {
                if (team.Count >= roles.Length) break;
                if (team.Count(id => info.First(h => h.Id == id).Role == role) >= roles.Count(r => r == role)) continue;
                var pool = others.Where(h => h.Role == role && !team.Contains(h.Id)).ToList();
                if (pool.Count > 0) team.Add(pool[rng.Range(0, pool.Count)].Id);
            }
            while (team.Count < roles.Length)
            {
                var pool = others.Where(h => !team.Contains(h.Id)).ToList();
                team.Add(pool[rng.Range(0, pool.Count)].Id);
            }
            return team;
        }

        static List<T> Shuffle<T>(List<T> l, Rng rng)
        {
            for (int i = l.Count - 1; i > 0; i--) { int j = rng.Range(0, i + 1); (l[i], l[j]) = (l[j], l[i]); }
            return l;
        }

        /// <summary>Lowest enemy level (1-200) at which the best reference team wins at most the stage's cap: 70%, or 55% in a
        /// chapter's last 5 stages. Binary search; win rate falls as the enemy levels up. Level 1 when even that is harder.</summary>
        public static int Calibrate(GameData g, StageDef s, List<List<string>> refs, int battles, ulong seed, out double winRate)
        {
            double cap = s.Stage <= 25 ? 0.70 : 0.55, floor = s.Stage <= 25 ? 0.50 : 0.40;
            int lo = 1, hi = 200;
            winRate = WinRate(g, s, hi, refs, battles, seed);
            if (winRate > cap) return hi;
            while (lo < hi)
            {
                int mid = (lo + hi) / 2;
                double wr = WinRate(g, s, mid, refs, battles, seed);
                if (wr <= cap) { hi = mid; winRate = wr; } else lo = mid + 1;
            }
            // Difficulty can jump steeply between neighbouring levels; never go below the band's floor (plan: win 50-70%).
            if (winRate < floor && hi > 1) { hi--; winRate = WinRate(g, s, hi, refs, battles, seed); }
            return hi;
        }

        /// <summary>Win rate of the best reference team: a player swaps to the team that counters the enemy (row 18; owner, 2026-10-03).</summary>
        public static double WinRate(GameData g, StageDef s, int enemyLevel, List<List<string>> refs, int battles, ulong seed)
        {
            int perTeam = Math.Max(1, battles / refs.Count);
            double best = 0;
            int pl = Expected.Level(s.Index), ps = Expected.Stars(s.Chapter);
            int el = Math.Clamp(enemyLevel, 1, 200);
            var enemy = new TeamSetup { Scales = new List<double>() };
            foreach (var e in s.Enemies) { enemy.Heroes.Add(e.Hero); enemy.Scales.Add(g.Progression.Mult(el, e.Stars)); }
            for (int t = 0; t < refs.Count; t++)
            {
                var player = new TeamSetup(refs[t].ToArray()) { Scales = refs[t].Select(_ => g.Progression.Mult(pl, ps)).ToList() };
                int wins = 0;
                for (int k = 0; k < perTeam; k++)
                {
                    var b = new Battle(g, player, enemy, seed * 7919UL + (ulong)(s.Index * 1000 + t * 100 + k)) { KeepLog = false };
                    if (b.Run().Winner == 0) wins++;
                }
                best = Math.Max(best, (double)wins / perTeam);
            }
            return best;
        }
    }
}
