"""Pass 0: first full draft of 60 heroes. Revisions are applied on top in revisions.py so every change is logged."""

def H(id, name, core, sub, role, style, rng, tgt, mv, look, ult, s1, s2, p, applies=(), payoffs=()):
    return dict(id=id, name=name, core=core, subrace=sub, role=role, style=style, range=rng, targeting=tgt, movement=mv, look=look,
                ultimate=dict(name=ult[0], text=ult[1], tags=list(ult[2])),
                skill1=dict(name=s1[0], cd=s1[1], text=s1[2], tags=list(s1[3])),
                skill2=dict(name=s2[0], cd=s2[1], text=s2[2], tags=list(s2[3])),
                passive=dict(name=p[0], text=p[1], tags=list(p[2])),
                applies=list(applies), payoffs=list(payoffs))

HEROES = [
# ===================== HIGH (gold dawn) =====================
H("valeria","Valeria","high","gilded","tank","Guardian","melee","Nearest","Walks to the front and holds",
  "Gold-filigree pauldron on one arm, white cape, sunlit marble stairs",
  ("Aegis of Dawn","Shields the team for 20% of her max HP and taunts all enemies for 3s.",["shield_aoe","taunt"]),
  ("Shield Bash",7,"Stuns the nearest enemy for 1s.",["cc_stun"]),
  ("Rally Banner",12,"Plants a banner: allies near it gain DEF up (30%) for 5s.",["buff_def"]),
  ("Bulwark","Allies behind her take 10% less damage.",["dr"]),
  applies=["Shielded","Taunted","Stunned","Buffed"], payoffs=[]),
H("solenne","Solenne","high","sun","dps","Marksman","ranged","Highest ATK","Holds long range",
  "Gold sun-disk halo, long bow of white bone, warm rim light",
  ("Noon Lance","A beam that pierces the whole row for 320% ATK.",["dmg_row"]),
  ("Sunshot",6,"Marks the target (takes +15% damage) for 4s.",["mark"]),
  ("Solar Flare",11,"Blinds enemies in a cone for 2s.",["debuff_blind"]),
  ("Glare","Crits blind for 2s.",["debuff_blind"]),
  applies=["Mark","Blind"], payoffs=[]),
H("aurelle","Aurelle","high","dawn","healer","Burst","ranged","Lowest-HP ally","Stays back",
  "Rose-gold first light, dew on bare shoulders, sheer white veil",
  ("First Light","Heals all for 30% and revives the first ally to fall in the next 8s.",["heal_aoe","revive"]),
  ("Radiance",6,"Big heal on one ally (250% ATK).",["heal_single"]),
  ("Morning Grace",10,"Heals the two weakest allies over 4s.",["heal_single"]),
  ("Overflow","Overhealing becomes a shield.",["shield_single"]),
  applies=["Shielded"], payoffs=[]),
H("seravelle","Seravelle","high","seraph","support","Buffer","ranged","Follows the strongest ally","Stays behind the carry",
  "White feathered wings, choir halo of floating gold rings",
  ("Choir of Wings","Team ATK up (25%) for 6s.",["buff_atk"]),
  ("Purify",8,"Cleanses one ally.",["cleanse"]),
  ("Feather Veil",14,"One ally becomes untargetable for 1.5s.",["untargetable"]),
  ("Hymn","Allies gain 10 energy when she casts a skill.",["buff_energy"]),
  applies=["Buffed","Energy"], payoffs=[]),
H("cassia","Cassia","high","templar","tank","Bruiser","melee","Highest ATK","Walks in",
  "White-silver plate with blood-red sacred banner, cropped silver hair",
  ("Sanctified Ground","Holy zone for 5s: allies inside heal 3% HP/s, enemies inside take 40% ATK/s.",["heal_aoe","dmg_aoe"]),
  ("Holy Strike",6,"Hits for 180% ATK and heals her for half.",["dmg_single"]),
  ("Judgement",12,"Strips all buffs from her target.",["dispel"]),
  ("Absolution","Each buff she removes gives her a shield of 5% max HP.",["shield_single"]),
  applies=["Dispel"], payoffs=["Dispel"]),
H("ilyra","Ilyra","high","phoenix","dps","Nuker","ranged","Densest enemy group","Mid range",
  "Gold-red plumage cloak, embers drifting upward, burnt-gold eyes",
  ("Rebirth Flame","Fire blast for 300% ATK on all; if she falls within 10s she revives at 30% (once).",["dmg_aoe","revive"]),
  ("Fire Plume",7,"Burning area for 3s.",["dot_burn"]),
  ("Wingbeat",12,"Knocks back nearby enemies.",["cc_knock"]),
  ("Pyre","Her burns stack up to three times.",["dot_burn"]),
  applies=["Burn"], payoffs=["Grouped"]),
H("elara","Elara","high","halo","healer","Cleanser","ranged","Most-debuffed ally","Stays back",
  "Floating halo, gold thread embroidery, calm downcast eyes",
  ("Halo of Grace","Heals all for 15% and grants control immunity for 4s.",["heal_aoe","immunity"]),
  ("Mending Light",6,"Heals the weakest ally over 4s.",["heal_single"]),
  ("Dispel Light",10,"Removes every debuff from one ally.",["cleanse"]),
  ("Haloed","Allies with her halo take 5% less damage.",["dr"]),
  applies=["Buffed"], payoffs=[]),
H("amarante","Amarante","high","choir","support","Dispeller","ranged","Most-buffed enemy","Holds range",
  "Hymn script glowing on sheer robes, gold bell earrings",
  ("Hymn of Unmaking","Strips all enemy buffs and silences them for 2s.",["dispel","cc_silence"]),
  ("Verdict",7,"Lowers her target's DEF by 30% for 5s.",["debuff_def"]),
  ("Bell Toll",11,"Stuns her target for 1s.",["cc_stun"]),
  ("Sentence","Enemies she debuffs deal 10% less damage.",["debuff_atk"]),
  applies=["Dispel","Weakened","Stunned"], payoffs=[]),
H("lucienne","Lucienne","high","sun","dps","Duelist","melee","Nearest blinded enemy, else nearest","Dashes in and duels",
  "Sunlit rapier, gold half-mask, one bare shoulder under a white mantle",
  ("Sunder Dawn","Dashes through a line of enemies for 280% ATK.",["dmg_row"]),
  ("Riposte",8,"Counter stance for 2s.",["counter"]),
  ("Glare",10,"Blinds the nearest enemy for 1.5s.",["debuff_blind"]),
  ("Blinding Edge","+40% crit damage against blinded enemies.",["dmg_single"]),
  applies=["Blind"], payoffs=["Blind"]),
H("ophira","Ophira","high","seraph","dps","Lancer","melee","Enemy carry (highest ATK)","Flies over the front line",
  "Seraph wings mid-beat, gold spear, white silk trailing",
  ("Judgement Spear","Falls from the sky on the enemy carry for 350% ATK and knocks up nearby enemies.",["dmg_single","cc_knock"]),
  ("Wing Cut",6,"Slashes for 160% ATK.",["dmg_single"]),
  ("Ascend",12,"Becomes airborne and untargetable for 1s.",["untargetable"]),
  ("Skyfall","+25% damage to airborne enemies.",["dmg_single"]),
  applies=["Airborne"], payoffs=["Airborne"]),
H("rosalind","Rosalind","high","gilded","support","Commander","ranged","Follows the main damage dealer","Stays mid-field",
  "Queen in gold court regalia, heavy chain jewellery, banner of the dawn",
  ("Royal Decree","Team ATK up (25%) for 6s and removes one debuff from each ally.",["buff_atk","cleanse"]),
  ("Knighting",8,"One ally gains DEF up (30%) for 5s.",["buff_def"]),
  ("Tithe",12,"Steals one buff from an enemy.",["dispel"]),
  ("Court of Dawn","Allies deal +3% damage per active buff they carry (max 5).",["buff_atk"]),
  applies=["Buffed","Dispel"], payoffs=["Buffed"]),
H("isolde","Isolde","high","templar","tank","Martyr","melee","Nearest","Stands beside the weakest ally",
  "Battered white plate, bandaged hands, candle-lit chapel",
  ("Martyrdom","For 4s she takes 50% of the damage dealt to allies.",["dr","taunt"]),
  ("Oathbound",8,"Links to the weakest ally; takes 25% of their damage for 5s.",["dr"]),
  ("Purifying Blade",10,"Hits for 150% ATK and cleanses herself.",["dmg_single","cleanse"]),
  ("Devotion","Heals and shields on her are 30% stronger.",["dr"]),
  applies=[], payoffs=["Shielded"]),

# ===================== DARK (crimson night) =====================
H("sangrael","Sangrael","dark","blood","tank","Bruiser","melee","Nearest","Walks into melee",
  "Crimson lace over black plate, red lips, blood-red rose in her hair",
  ("Crimson Feast","Drains 120% ATK from every nearby enemy.",["dmg_aoe","heal_single"]),
  ("Blood Oath",8,"Taunts nearby enemies and gains Lifesteal up for 4s.",["taunt","buff_lifesteal"]),
  ("Bloodletting",10,"Cleaves nearby enemies and makes them bleed.",["dot_bleed"]),
  ("Last Rites","Below 30% HP she takes 25% less damage.",["dr"]),
  applies=["Taunted","Bleed","Lifesteal"], payoffs=["Lifesteal"]),
H("nyx","Nyx","dark","shadow","dps","Assassin","melee","Lowest-HP back-row enemy","Dives",
  "Black veils, silver throat chain, half her face in shadow",
  ("Night's Edge","Blinks to the weakest enemy and executes them below 20% HP.",["execute"]),
  ("Fade",9,"Stealth for 2s.",["untargetable"]),
  ("Shadowstep",8,"Teleports behind her target; her next hit always crits.",["dmg_single"]),
  ("Backstab","+40% crit damage from behind or from stealth.",["dmg_single"]),
  applies=[], payoffs=["Stealth","LowHP"]),
H("vesper","Vesper","dark","raven","healer","Drain","ranged","Enemy nearest the weakest ally","Mid range",
  "Raven-feather mantle, black crows circling, moonlit pale skin",
  ("Murder of Crows","Ravens hit all enemies and heal the team for 60% of the damage.",["dmg_aoe","heal_aoe"]),
  ("Feeding Curse",7,"Curses an enemy: allies heal whenever it is hit.",["curse"]),
  ("Raven's Watch",11,"A raven guards the weakest ally and absorbs one hit.",["shield_single"]),
  ("Carrion","Her heals are 20% stronger on allies below half HP.",["heal_single"]),
  applies=["Curse"], payoffs=[]),
H("liora","Liora","dark","ember","support","Debuffer","ranged","Highest ATK enemy","Mid range",
  "Ember-cracked obsidian jewellery, smoke curling from her fingertips",
  ("Vermilion Rite","Burns all enemies for 4s and lowers their DEF by 20%.",["dot_burn","debuff_def"]),
  ("Ember Sigil",8,"Marks the highest-ATK enemy and drains 30 of their energy.",["energy_drain","mark"]),
  ("Cinder Veil",10,"Smoke on the enemy back row: enemies inside miss 20% of attacks for 4s.",["debuff_blind"]),
  ("Ashen Wound","Burning enemies receive 30% less healing.",["debuff_antiheal"]),
  applies=["Burn","Weakened","Blind"], payoffs=["Burn"]),
H("corvina","Corvina","dark","grave","tank","Undying","melee","Nearest","Holds the front",
  "Bone-lace corset, skull circlet, candles in a crypt",
  ("Grave Rise","Can't drop below 1 HP for 4s and taunts all.",["unkillable","taunt"]),
  ("Bone Wall",9,"Shields herself for 20% max HP.",["shield_single"]),
  ("Death Grip",12,"Drags the nearest back-row enemy forward.",["pull"]),
  ("Mourning","When an ally falls, she gains a shield worth 20% max HP.",["shield_single"]),
  applies=["Taunted","Isolated"], payoffs=["Kill"]),
H("maelis","Maelis","dark","ash","dps","Warlock","ranged","Highest-HP enemy","Mid range",
  "Ash-grey hair, cinder runes on her forearms, smouldering hem",
  ("Ashfall","Smouldering ash on all enemies for 6s (burn).",["dot_burn","dmg_aoe"]),
  ("Hex Bolt",6,"Hits for 170% ATK and curses.",["dmg_single","curse"]),
  ("Soot",11,"Blinds one enemy for 2s.",["debuff_blind"]),
  ("Smoulder","+25% damage to burning or cursed enemies.",["dmg_single"]),
  applies=["Burn","Curse","Blind"], payoffs=["Burn","Curse"]),
H("thessaly","Thessaly","dark","shadow","healer","Veil","ranged","Lowest-HP ally","Stays back",
  "Smoke-black gown, silver crescent pins, eyes closed in prayer",
  ("Night Veil","Heals all for 20% and hides them for 2s.",["heal_aoe","untargetable"]),
  ("Dark Mend",6,"Heals one ally and gives DEF up for 4s.",["heal_single","buff_def"]),
  ("Soul Tether",12,"Links two allies to share damage for 5s.",["dr"]),
  ("Night Tithe","Each heal she gives grants the target 5 energy.",["buff_energy"]),
  applies=["Stealth","Energy"], payoffs=[]),
H("velisande","Velisande","dark","blood","support","Anti-heal","ranged","Enemy healer first","Holds range",
  "Blood-moon crown, crimson silk, a goblet of dark wine",
  ("Dread","Fears all enemies for 2s.",["cc_fear"]),
  ("Blood Moon",9,"Team Lifesteal up (15%) for 5s.",["buff_lifesteal"]),
  ("Wither",10,"Target receives 50% less healing for 5s.",["debuff_antiheal"]),
  ("Terror","Feared enemies take 10% more damage.",["debuff_weaken"]),
  applies=["Feared","Lifesteal"], payoffs=["Feared"]),
H("ravenna","Ravenna","dark","blood","dps","Bleed duelist","melee","Nearest bleeding enemy, else nearest","Weaves through melee",
  "Twin crimson sabres, blood-red silk wrapping, bare back with black-ink tattoos",
  ("Crimson Waltz","Six slashes on nearby enemies, each applying Bleed.",["dmg_aoe","dot_bleed"]),
  ("Lacerate",6,"Hits for 160% ATK and makes the target bleed.",["dot_bleed"]),
  ("Blood Rush",11,"Attack speed up (40%) for 4s.",["buff_speed"]),
  ("Sanguine Edge","+20% damage to bleeding enemies; hitting one heals her 3% max HP.",["dmg_single"]),
  applies=["Bleed"], payoffs=["Bleed"]),
H("sable","Sable","dark","raven","dps","Reaper","melee","Lowest-HP enemy","Walks the front line",
  "Raven-wing scythe, black feathers drifting, pale skull mask pushed up",
  ("Harvest","Scythe sweep that deals 400% ATK to every enemy below 40% HP; each kill refunds 50 energy.",["execute","dmg_aoe"]),
  ("Reap",7,"Cleaves the front row for 150% ATK.",["dmg_row"]),
  ("Carrion Birds",11,"Ravens peck the weakest enemy, causing Bleed.",["dot_bleed"]),
  ("Death's Due","Gains 10 energy whenever any enemy falls.",["buff_energy"]),
  applies=["Bleed","Kill"], payoffs=["LowHP","Kill"]),
H("noctelle","Noctelle","dark","shadow","support","Shadowbinder","ranged","Follows the assassin","Stays out of sight",
  "Indigo-black veil, moth-wing hairpins, a single candle",
  ("Eclipse","All allies stealth for 2s; their first hit after stealth always crits.",["untargetable","buff_crit"]),
  ("Shade",9,"One ally stealths for 1.5s.",["untargetable"]),
  ("Smother",12,"Silences her target for 1.5s.",["cc_silence"]),
  ("From the Dark","Allies attacking from stealth deal +15% damage.",["buff_atk"]),
  applies=["Stealth"], payoffs=["Stealth"]),
H("mordessa","Mordessa","dark","blood","healer","Lifebinder","ranged","Lowest-HP ally","Stays back",
  "Black velvet, ruby choker, blood rising in red ribbons",
  ("Sanguine Covenant","Team Lifesteal up (30%) for 6s and heals all for 10%.",["buff_lifesteal","heal_aoe"]),
  ("Transfusion",7,"Spends 10% of her HP to heal an ally for 25%.",["heal_single"]),
  ("Bloodbond",12,"Links two allies: 20% of damage they take is healed back.",["heal_single"]),
  ("Red Tide","Gains energy whenever an ally heals through lifesteal.",["buff_energy"]),
  applies=["Lifesteal"], payoffs=["Lifesteal"]),

# ===================== NATURE (dappled emerald) =====================
H("hartwen","Hartwen","nature","stag","tank","Gatherer","melee","Nearest","Charges in",
  "Antler crown woven with gold leaf, moss cloak, dappled forest light",
  ("Grove's Embrace","Vines pull every enemy to the centre and root them for 2s.",["pull","cc_root"]),
  ("Antler Charge",7,"Knocks up the first enemy hit.",["cc_knock"]),
  ("Thicket",11,"Roots the nearest enemy for 1.5s and taunts.",["cc_root","taunt"]),
  ("Evergreen","Regenerates 2% HP per second.",["regen"]),
  applies=["Grouped","Rooted","Airborne","Taunted"], payoffs=[]),
H("kaida","Kaida","nature","wild","dps","Summoner","melee","Nearest","Fights beside her wolves",
  "Wolf-pelt mantle, war paint, amber eyes, wolves at her heels",
  ("Pack Hunt","Summons two wolves for 10s.",["summon"]),
  ("Pounce",8,"Leaps onto a back-row enemy.",["dmg_single"]),
  ("Howl",12,"She and her wolves attack 20% faster for 5s.",["buff_speed"]),
  ("Pack Leader","+15% damage while a beast is out.",["dmg_single"]),
  applies=["Summon"], payoffs=["Summon"]),
H("mireille","Mireille","nature","wood","healer","Regen","ranged","Lowest-HP ally","Stays back",
  "Flowers blooming in her hair, gold-leaf freckles, sheer green silk",
  ("Bloomfall","Heals all over 8s and removes debuffs.",["heal_aoe","cleanse"]),
  ("Thorn Shield",7,"Shields one ally; attackers take 20% ATK damage.",["shield_single","reflect"]),
  ("Seed of Life",12,"Plants a seed that heals an ally the moment they drop below 30%.",["heal_single"]),
  ("Verdant","Heals are 20% stronger on allies below half HP.",["heal_single"]),
  applies=["Shielded"], payoffs=[]),
H("fenna","Fenna","nature","fae","support","Controller","ranged","Densest enemy group","Holds range",
  "Iridescent butterfly wings, petals caught in her hair, dreamy half-smile",
  ("Midsummer Dream","Puts all enemies to sleep for 2.5s (damage wakes them).",["cc_sleep"]),
  ("Glamour",9,"Creates a decoy that draws attacks for 3s.",["taunt"]),
  ("Pollen Haze",11,"Slows enemies in an area for 3s.",["debuff_slow"]),
  ("Fae Step","Allies near her dodge 10% of attacks.",["dr"]),
  applies=["Asleep","Slow","Grouped"], payoffs=[]),
H("briar","Briar","nature","thorn","tank","Thorns","melee","Nearest","Walks to the front",
  "Briar-thorn armour, blood-red roses, scratches on pale skin",
  ("Wall of Briars","Barrier that reflects 30% of damage for 4s.",["reflect","dr"]),
  ("Thorn Lash",7,"Taunts and makes the target bleed.",["taunt","dot_bleed"]),
  ("Root Hold",12,"Plants herself and gains DEF up (60%) for 3s.",["buff_def"]),
  ("Bramble Skin","Reflects 15% of melee damage.",["reflect"]),
  applies=["Taunted","Bleed"], payoffs=["Taunted"]),
H("sylwen","Sylwen","nature","owl","dps","Marksman","ranged","Lowest-HP enemy","Holds long range",
  "Owl-feather cape, gold-tipped arrows, moonlit eyes",
  ("Owl's Eye","Three shots at the weakest enemies, each ignoring 30% DEF.",["dmg_single","execute"]),
  ("Pinning Arrow",7,"Roots her target for 1s.",["cc_root"]),
  ("Volley",10,"Rains arrows on an area.",["dmg_aoe"]),
  ("Night Sight","Sees through stealth; +10% crit at long range.",["dmg_single"]),
  applies=["Rooted"], payoffs=["LowHP","Rooted"]),
H("nimue","Nimue","nature","willow","healer","Reviver","ranged","Lowest-HP ally","Stays back",
  "Long weeping-willow hair to her knees, river-wet silk",
  ("Return to Roots","Revives one fallen ally at 40% HP.",["revive"]),
  ("Willow Touch",6,"Heals one ally.",["heal_single"]),
  ("Sap Shield",10,"Shields one ally.",["shield_single"]),
  ("Deep Roots","Allies below 20% HP take 20% less damage.",["dr"]),
  applies=["Shielded"], payoffs=[]),
H("zephyra","Zephyra","nature","moth","support","Speed buffer","ranged","Follows the fastest ally","Flits around",
  "Dusky moth wings, lantern light, ash-blonde braids",
  ("Moonmoth Dance","Team Attack speed up (30%) for 5s.",["buff_speed"]),
  ("Dream Dust",9,"Puts one enemy to sleep for 2s.",["cc_sleep"]),
  ("Lantern Glow",11,"Gives an ally 20 energy.",["buff_energy"]),
  ("Moth Light","Allies near her gain 5% crit chance.",["buff_crit"]),
  applies=["Buffed","Energy","Asleep"], payoffs=[]),
H("rhiannon","Rhiannon","nature","wild","dps","Beastmaster","melee","Her beast's target","Fights with a stag spirit",
  "Bare-shouldered huntress, antlered spirit stag of green light beside her",
  ("Stampede","Spirit beasts charge through a row for 260% ATK and knock up.",["dmg_row","cc_knock"]),
  ("Command",6,"Her stag spirit gores the target for 180% ATK.",["dmg_single"]),
  ("Feral Bond",12,"She and all allied summons gain ATK up (25%) for 5s.",["buff_atk"]),
  ("Spirit Stag","A spirit stag fights beside her all battle.",["summon"]),
  applies=["Summon","Airborne"], payoffs=["Summon"]),
H("venna","Venna","nature","thorn","dps","Poisoner","ranged","Highest-HP enemy","Mid range",
  "Nightshade blossoms, green-black lips, poison vials on a gold belt",
  ("Nightshade Bloom","Poisons all enemies (4% max HP/s) for 4s.",["dot_poison"]),
  ("Toxic Dart",6,"Poisons the target (2%/s) for 4s.",["dot_poison"]),
  ("Spore Burst",11,"Area poison and slow for 3s.",["dot_poison","debuff_slow"]),
  ("Contagion","When a poisoned enemy falls, the poison jumps to a nearby enemy.",["dot_poison"]),
  applies=["Poison","Slow"], payoffs=["Kill"]),
H("wren","Wren","nature","fae","support","Hexer","ranged","Rooted enemy, else nearest","Holds range",
  "Tiny fae ring of mushrooms, glimmering wings, mischievous grin",
  ("Faerie Ring","Enemies inside the ring are Weakened (+25% damage taken) for 5s.",["debuff_weaken"]),
  ("Snare",8,"Roots her target for 1.5s.",["cc_root"]),
  ("Glimmer",10,"Cleanses one debuff from an ally.",["cleanse"]),
  ("Snared Prey","Rooted enemies take +10% damage.",["debuff_weaken"]),
  applies=["Weakened","Rooted"], payoffs=["Rooted"]),
H("eldrith","Eldrith","nature","wood","tank","Heartwood","melee","Nearest","Plants herself at the front",
  "Bark-like skin patterns, ancient oak crown, moss and gold leaf",
  ("Heartwood","Becomes an ancient tree for 5s: taunts all, regenerates 10% HP/s, can't move.",["taunt","regen"]),
  ("Bark Skin",8,"DEF up (30%) for 5s.",["buff_def"]),
  ("Grasping Roots",11,"Roots the two nearest enemies for 1.5s.",["cc_root"]),
  ("Old Growth","Heals she receives are 25% stronger.",["regen"]),
  applies=["Taunted","Rooted"], payoffs=["Shielded"]),

# ===================== OCEAN (deep sea-blue) =====================
H("thalassa","Thalassa","ocean","abyss","tank","Disruptor","melee","Nearest","Walks to the front",
  "Anchor chain over dark plate, wet black hair, bioluminescent freckles",
  ("Undertow","Knocks the enemy front row back and slows them for 3s.",["cc_knock","debuff_slow"]),
  ("Anchor Slam",8,"Stuns for 1s.",["cc_stun"]),
  ("Riptide",12,"Drags one back-row enemy to the front.",["pull"]),
  ("Barnacle","Reflects 10% of melee damage.",["reflect"]),
  applies=["Slow","Stunned","Isolated"], payoffs=[]),
H("halcyra","Halcyra","ocean","storm","dps","Chain caster","ranged","Random","Holds range",
  "Storm-grey hair whipping, lightning in her palms, torn sea-silk",
  ("Tempest","Chain lightning that bounces six times for 140% ATK each.",["dmg_aoe"]),
  ("Static Mark",6,"Her next hit on the target bounces.",["dmg_single"]),
  ("Thunderclap",11,"Stuns enemies around the target for 0.5s.",["cc_stun"]),
  ("Arc","Crits bounce once.",["dmg_aoe"]),
  applies=["Stunned"], payoffs=[]),
H("odette","Odette","ocean","pearl","healer","Shield","ranged","Lowest-HP ally","Stays back",
  "Pearl strands across her collarbones, nacre armour, moonlit water",
  ("Pearl Ward","Shields the team for 25% of their max HP.",["shield_aoe"]),
  ("Bubble",6,"Heals one ally and shields them.",["heal_single","shield_single"]),
  ("Tidal Cleanse",11,"Removes debuffs from all allies.",["cleanse"]),
  ("Nacre","Shielded allies resist control effects.",["immunity"]),
  applies=["Shielded"], payoffs=["Shielded"]),
H("lorelei","Lorelei","ocean","siren","support","Charmer","ranged","Highest ATK enemy","Holds range",
  "Sea-glass scales on her hips, wet silk, a haunting open-mouthed song",
  ("Siren Song","Charms two enemies for 3s.",["cc_charm"]),
  ("Lullaby",8,"Drains 25 energy from one enemy.",["energy_drain"]),
  ("Hush",12,"Silences the enemy with the most energy for 2s.",["cc_silence"]),
  ("Undertone","Enemies she hits lose 5 energy.",["energy_drain"]),
  applies=["Charmed"], payoffs=[]),
H("coralie","Coralie","ocean","coral","tank","Guardian","melee","Nearest","Holds the front",
  "Coral crown, reef-coloured scale armour, shell pauldron",
  ("Tidal Bulwark","A wall of water blocks enemy projectiles for 3s.",["dr"]),
  ("Shell Guard",8,"Shields herself and the nearest ally.",["shield_single"]),
  ("Tidecall",12,"Taunts all enemies for 2s.",["taunt"]),
  ("Reef Hide","20% chance to block an attack.",["dr"]),
  applies=["Shielded","Taunted"], payoffs=[]),
H("nerissa","Nerissa","ocean","mermaid","dps","Diver","melee","Lowest-HP enemy","Glides above the field",
  "Mermaid tail glinting teal, trident, wet hair across bare shoulders",
  ("Maelstrom","A whirlpool pulls in and damages enemies for 3s.",["pull","dmg_aoe"]),
  ("Trident Dive",7,"Dives onto the back row for 200% ATK.",["dmg_single"]),
  ("Undercurrent",10,"Slows her target by 30% for 3s.",["debuff_slow"]),
  ("Hunting Waters","+20% damage to slowed enemies.",["dmg_single"]),
  applies=["Grouped","Slow"], payoffs=["Slow"]),
H("marisol","Marisol","ocean","rain","healer","Regen","ranged","Lowest-HP ally","Stays back",
  "Rain-soaked silk, paper umbrella, droplets lit like pearls",
  ("Monsoon","All allies heal 4% max HP/s for 6s.",["heal_aoe","regen"]),
  ("Raindrop",6,"Heals one ally.",["heal_single"]),
  ("Wash Away",10,"Removes debuffs from two allies.",["cleanse"]),
  ("Overflow Tide","Overhealing becomes energy.",["buff_energy"]),
  applies=["Energy"], payoffs=[]),
H("ondine","Ondine","ocean","kraken","support","Debuffer","ranged","Highest ATK enemy","Holds range",
  "Ink-black tentacle motifs on a deep-blue gown, inky veil",
  ("Ink Cloud","Blinds all enemies (miss 50%) for 3s.",["debuff_blind"]),
  ("Tentacle Grasp",8,"Stuns for 1s.",["cc_stun"]),
  ("Brine",10,"Lowers her target's DEF by 30% for 5s.",["debuff_def"]),
  ("Ink Bitten","Blinded enemies take 10% more damage.",["debuff_weaken"]),
  applies=["Blind","Weakened","Stunned"], payoffs=["Blind"]),
H("ysra","Ysra","ocean","storm","dps","Stormcaller","ranged","Soaked enemy, else highest ATK","Holds long range",
  "Lightning-veined skin, spear of sea-glass, storm clouds overhead",
  ("Skybreaker","A bolt strikes every enemy for 220% ATK.",["dmg_aoe"]),
  ("Arc Shot",6,"Hits for 170% ATK.",["dmg_single"]),
  ("Squall",11,"Drenches enemies in an area for 4s.",["dmg_aoe"]),
  ("Conductor","Her hits on stunned enemies deal +25%.",["dmg_single"]),
  applies=[], payoffs=["Stunned"]),
H("calypso","Calypso","ocean","abyss","dps","Lurker","melee","Isolated enemy, else carry","Lurks then strikes",
  "Abyssal anglerfish lantern above her head, black-blue skin sheen",
  ("Lure of the Deep","Pulls the enemy carry to her and devours them for 380% ATK, healing for half.",["pull","dmg_single"]),
  ("Bite",6,"Hits for 170% ATK.",["dmg_single"]),
  ("Lantern",12,"Charms one enemy for 1.5s.",["cc_charm"]),
  ("Deep Hunger","+25% damage to isolated enemies (no ally within 2 m).",["dmg_single"]),
  applies=["Isolated","Charmed"], payoffs=["Isolated"]),
H("pelagia","Pelagia","ocean","pearl","support","Tidecaller","ranged","Densest enemy group","Holds range",
  "Pearl diadem, sea-foam lace train, waves breaking behind her",
  ("High Tide","Drenches and pushes back all enemies; allies gain 20 energy.",["cc_knock","buff_energy"]),
  ("Spray",8,"Drenches and slows one enemy.",["debuff_slow"]),
  ("Clear Water",10,"Cleanses one ally.",["cleanse"]),
  ("Brine Weight","Slowed enemies attack 15% slower.",["debuff_slow"]),
  applies=["Slow","Energy"], payoffs=[]),
H("siora","Siora","ocean","siren","healer","Songweaver","ranged","Lowest-HP ally","Stays back",
  "Siren healer, pearl comb, eyes closed mid-song, faint teal glow",
  ("Requiem of the Tide","Sings for 4s: allies heal 5% HP/s and take 20% less damage.",["heal_aoe","dr"]),
  ("Hum",6,"Heals one ally.",["heal_single"]),
  ("Echo",10,"Repeats her last heal at 50% on another ally.",["heal_single"]),
  ("Cadence","Her heals give the target Attack speed up (15%) for 3s.",["buff_speed"]),
  applies=["Buffed"], payoffs=[]),

# ===================== ARCANE (indigo starlight) =====================
H("vaela","Vaela","arcane","void","tank","Warden","melee","Nearest","Holds the front",
  "Void-black armour with starlight seams, floating rune rings",
  ("Event Horizon","A zone absorbs all projectiles for 3s, then pulls enemies in.",["dr","pull"]),
  ("Rune Barrier",9,"Shields herself.",["shield_single"]),
  ("Gravity Well",12,"Pulls nearby enemies to her and taunts for 2s.",["pull","taunt"]),
  ("Null","Takes 15% less damage from ultimates.",["dr"]),
  applies=["Grouped","Taunted"], payoffs=[]),
H("astraea","Astraea","arcane","star","dps","Nuker","ranged","Densest enemy group","Holds long range",
  "Constellation tattoos, starlight freckles, indigo robes",
  ("Starfall","Huge area blast for 360% ATK.",["dmg_aoe"]),
  ("Meteor",7,"Heavy hit on one target for 200% ATK.",["dmg_single"]),
  ("Comet Trail",11,"A line of burning ground for 3s.",["dot_burn"]),
  ("Gravity Lens","+20% damage to enemies standing close together.",["dmg_aoe"]),
  applies=["Burn"], payoffs=["Grouped","Energy"]),
H("selene","Selene","arcane","moon","healer","Rewind","ranged","Ally who lost the most HP recently","Stays back",
  "Moon-fragment jewellery, silver hair, crescent-shaped halo",
  ("Moonrewind","Returns each ally to their HP from 3s earlier.",["heal_aoe"]),
  ("Moonbeam",6,"Heals one ally.",["heal_single"]),
  ("Crescent Ward",10,"Shields the weakest ally; heals them when it breaks.",["shield_single"]),
  ("Waning","Her heals also cleanse one debuff.",["cleanse"]),
  applies=["Shielded"], payoffs=[]),
H("elowen","Elowen","arcane","time","support","Energy battery","ranged","Follows the ally closest to a full ultimate","Stays mid-field",
  "Hourglass pendant, clockwork rings floating around her wrists",
  ("Quickening","Allies gain 40 energy and Attack speed up (20%) for 5s.",["buff_energy","buff_speed"]),
  ("Slow Time",8,"Slows one enemy for 3s.",["debuff_slow"]),
  ("Hasten",11,"One ally Attack speed up (30%) for 4s.",["buff_speed"]),
  ("Chronoflow","Allies near her gain energy 10% faster.",["buff_energy"]),
  applies=["Energy","Slow","Buffed"], payoffs=[]),
H("draxa","Draxa","arcane","dragon","tank","Shapeshifter","melee","Nearest","Walks in",
  "Horns and scales along her spine, slit-pupil gold eyes, smoke at her lips",
  ("Dragonform","Becomes a dragon for 8s: +50% HP and a fire-breath attack.",["buff_def","dot_burn"]),
  ("Scale Guard",8,"DEF up (30%) for 5s.",["buff_def"]),
  ("Tail Sweep",11,"Knocks back nearby enemies.",["cc_knock"]),
  ("Dragonblood","Immune to burns.",["immunity"]),
  applies=["Burn"], payoffs=[]),
H("caelith","Caelith","arcane","rune","dps","Tank-breaker","ranged","Highest-HP enemy","Holds range",
  "Carved stone runes along her arms, rune-light in her eyes",
  ("Unraveling","Three hits that each deal 15% of the target's max HP.",["dmg_single"]),
  ("Rune Bolt",6,"A magic bolt for 170% ATK.",["dmg_single"]),
  ("Spellbreak",11,"Strips one buff and silences for 1s.",["dispel","cc_silence"]),
  ("Unbind","+30% damage to shields.",["dmg_single"]),
  applies=["Dispel"], payoffs=[]),
H("lunaith","Lunaith","arcane","dream","healer","Warder","ranged","Lowest-HP ally","Stays back",
  "Dream-haze pastel smoke, silver eyelashes, sleeping moth on her finger",
  ("Lucid Dream","Heals all for 25% and grants control immunity for 5s.",["heal_aoe","immunity"]),
  ("Dream Mend",6,"Heals one ally.",["heal_single"]),
  ("Drowse",11,"Puts one enemy to sleep for 2s.",["cc_sleep"]),
  ("Reverie","Her heals grant 10 energy.",["buff_energy"]),
  applies=["Asleep","Energy"], payoffs=[]),
H("seren","Seren","arcane","star","support","Crit buffer","ranged","Follows the main damage dealer","Stays mid-field",
  "Star-map gown, astrolabe in hand, starlight particles",
  ("Constellation","Team Crit up (30%) for 6s.",["buff_crit"]),
  ("Star Map",8,"Marks a target (takes +15% damage) for 5s.",["mark"]),
  ("Fate's Thread",12,"30% of damage an ally takes is copied back to the attacker for 5s.",["reflect"]),
  ("Fortune","Allies near her deal +10% crit damage.",["buff_crit"]),
  applies=["Mark","Buffed"], payoffs=[]),
H("isaura","Isaura","arcane","void","dps","Mana thief","ranged","Enemy with the most energy","Mid range",
  "Void-purple hair, a black orb drinking light, starless eyes",
  ("Null Field","Drains 40 energy from all enemies and deals 5% ATK per energy drained.",["energy_drain","dmg_aoe"]),
  ("Siphon",6,"Steals 15 energy from her target.",["energy_drain"]),
  ("Blink",10,"Teleports out of danger.",["untargetable"]),
  ("Hunger of the Void","+2% damage per 10 energy she has stolen this battle (max +30%).",["dmg_single"]),
  applies=[], payoffs=[]),
H("zaria","Zaria","arcane","dragon","dps","Dragonrider","ranged","Densest enemy group","Rides above the back line",
  "Dragonrider in gold-scale harness, a small indigo dragon coiled around her",
  ("Wyrmfire","Dragon breath in a cone for 280% ATK, applying Burn.",["dmg_aoe","dot_burn"]),
  ("Claw",6,"Her dragon claws the target for 170% ATK.",["dmg_single"]),
  ("Ember Wing",11,"Burns a row of enemies.",["dot_burn"]),
  ("Kindled","+20% damage to burning enemies.",["dmg_single"]),
  applies=["Burn"], payoffs=["Burn"]),
H("tempra","Tempra","arcane","time","support","Chronomancer","ranged","Follows the ally with the longest cooldowns","Stays mid-field",
  "Clock-face halo, sand drifting from her sleeves, silver hourglass",
  ("Rewind Clocks","Resets all allies' skill cooldowns.",["buff_cdr"]),
  ("Accelerate",8,"One ally gains Haste up (+30) for 4s.",["buff_cdr"]),
  ("Stasis",12,"Freezes an enemy in time for 1.5s (they can't be damaged either).",["cc_stun"]),
  ("Timekeeper","Allies' skills recharge 10% faster.",["buff_cdr"]),
  applies=["Cooldown"], payoffs=[]),
H("runa","Runa","arcane","rune","tank","Rune golem","melee","Nearest","Holds the front",
  "Runic stone plates fused to silk, glowing glyphs, cracked-porcelain skin",
  ("Runic Aegis","All allies gain a Skill shield (blocks the next skill or ultimate hit).",["shield_aoe"]),
  ("Rune Ward",9,"Shields herself.",["shield_single"]),
  ("Counterspell",12,"Silences the nearest enemy for 1.5s.",["cc_silence"]),
  ("Glyph Mirror","Reflects 20% of skill damage.",["reflect"]),
  applies=["Shielded"], payoffs=[]),
]
